### ISSUE TITLE
adapter les fonctions de views

### ISSUE THREAD

**Issue by NathanBourdere** [NathanBourdere/SAE3.05_grp_NathanBourdere_2A#44]

**Comment by BryanBlinDorard** [comment]
faut que je fasse quoi concrètement ?

**Comment by NathanBourdere** [comment]
Il faut que tu corriges les fonctions de views où il y avait des lignes de codes qui étaient censés être dans la BD, donc dans le fichier models, tu as juste à enlever les lignes correspondante et mettre et utiliser les fonctions que Constantin aura crée, (d'où le travail de pair puisque cela n'est pas possible à faire sans que Constantin communique sur quelles lignes il a retiré et quels sont les noms des fonctions)
