### ISSUE TITLE
Gestion des erreurs et robustesse de l'application

### ISSUE THREAD

**Issue by NathanBourdere** [NathanBourdere/SAE3.05_grp_NathanBourdere_2A#89]
faire des crash tests pour faire en sorte de trouver des erreurs qui feraient crasher l'appli et gérer ceux-ci (avec des try et except, et des envois de messages d'erreurs au client) et patterns/regex

**Comment by closzach** [comment]
### Erreurs à règler :
- Problème lorsque que l'on entre les mêmes informations pour un vacataire. Vérifier toutes les contraintes d'unicité de la base de données et encadrer les blocs de codes concernée par des try/catch.

**Comment by Theo-Viard** [comment]
> ### Erreurs à règler :
> * Problème lorsque que l'on entre les mêmes informations pour un vacataire. Vérifier toutes les contraintes d'unicité de la base de données et encadrer les blocs de codes concernée par des try/catch.

Corrigé

**Comment by BryanBlinDorard** [comment]
Quand on est sur la page matière, si on enlève toutes les matières, on peut plus en rajouter.

Voila l'erreur
![Capture d’écran_2023-03-01_09-08-09](https://user-images.githubusercontent.com/113012471/222080748-38d9db28-42b5-4504-b791-8ab7abe2982b.png)

Cause probable : Quand il regarde si il y a déja des matières, il comprend pas et donc rien ne marche.

**Comment by BryanBlinDorard** [comment]
La même pour les disponibilités

**Comment by Theo-Viard** [comment]
> Quand on est sur la page matière, si on enlève toutes les matières, on peut plus en rajouter.
> 
> Voila l'erreur ![Capture d’écran_2023-03-01_09-08-09](https://user-images.githubusercontent.com/113012471/222080748-38d9db28-42b5-4504-b791-8ab7abe2982b.png)
> 
> Cause probable : Quand il regarde si il y a déja des matières, il comprend pas et donc rien ne marche.

Corrigé
